parse_config:
  raw_binding_map:
    '&bootloader': "RESET"
    '&kp RG(PLUS)': "Zoom In"
    '&kp RG(KP_SUBTRACT)': "Zoom Out"
    '&kp LS(LG(N5))': "SCREEN SHOT"
    '&kp KP_MINUS': "-"
    '&studio_unlock': "Studio Unlock"

  zmk_keycode_map:
    # custom mappings
    C_VOLUME_UP: Vol Up
    C_VOLUME_DOWN: Vol Down
    K_MUTE: Mute

    LCTRL: Ctrl
    RCTRL: Ctrl
    LEFT_ALT: Alt
    RIGHT_ALT: Alt
    LEFT_COMMAND: CMD
    RIGHT_COMMAND: CMD
    LEFT_SHIFT: Shift
    RIGHT_SHIFT: Shift
    ESC: Esc
    SPACE: SPACE
    BACKSPACE: BACK
    RET: ENTER
    TAB: TAB
    DEL: DEL

    UP_ARROW: UP
    DOWN_ARROW: DOWN
    LEFT_ARROW: LEFT
    RIGHT_ARROW: RIGHT

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
draw_config:
  dark_mode: auto
  separate_combo_diagrams: true
