on: 
  pull_request:
  workflow_dispatch:
  push: 
    paths:
      - "config/**"
      - ".github/workflows/build.yml"
      - "zephyr/module.yml"
      - "build.yaml"
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
